toolbar:
  - styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image
plugins:
  - advlist autolink lists link image charmap print preview anchor
  - searchreplace visualblocks code fullscreen
  - insertdatetime media table contextmenu paste code